<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE langileak [
    <!ELEMENT langileak (langilea+)>
    <!ELEMENT langilea (izena, abizena, emaila, telefonoa, data, nagusia?, lanpostua?, erabiltzailea?, pasahitza?)>
    <!ATTLIST langilea
        id CDATA #REQUIRED
        mota (bulegaria|saltzailea) #REQUIRED
    >
    <!ELEMENT izena (#PCDATA)>
    <!ELEMENT abizena (#PCDATA)>
    <!ELEMENT emaila (#PCDATA)>
    <!ELEMENT telefonoa (#PCDATA)>
    <!ELEMENT data (#PCDATA)>
    <!ELEMENT nagusia (izenAbizena)>
    <!ATTLIST nagusia id CDATA #REQUIRED>
    <!ELEMENT izenAbizena (#PCDATA)>
    <!ELEMENT lanpostua (#PCDATA)>
    <!ATTLIST lanpostua id CDATA #REQUIRED>
    <!ELEMENT erabiltzailea (#PCDATA)>
    <!ELEMENT pasahitza (#PCDATA)>
]>
<langileak>
    <langilea id="12345678" mota="bulegaria">
        <izena>Ane</izena>
        <abizena>Garcia</abizena>
        <emaila>ane.garcia@example.com</emaila>
        <telefonoa>9.43.555.111</telefonoa>
        <data>2025-01-15</data>

        <nagusia id="87654321">
            <izenAbizena>Jon Etxeberria</izenAbizena>
        </nagusia>

        <lanpostua id="LP01">Administraria</lanpostua>
    </langilea>

    <langilea id="23456789" mota="saltzailea">
        <izena>Iker</izena>
        <abizena>Lopez</abizena>
        <emaila>iker.lopez@example.com</emaila>
        <telefonoa>6.11.222.333</telefonoa>
        <data>2024-11-03</data>

        <erabiltzailea>ikerl</erabiltzailea>
        <pasahitza>Secreta123</pasahitza>
    </langilea>
</langileak>
